name: Scheduled build

on:
  schedule:
    - cron: '0 0-23/4 * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl --show-error -X POST -d {} "${{ secrets.BUILD_HOOK_URL }}"
